## PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  capacity:          
    storage: 100Gi
  accessModes:       
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - hard
  - nfsvers=4.1    
  nfs:
    server: 192.168.2.11
    path: /nfs/gitlab/git
---
## PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab
spec:
  resources:
    requests:
      storage: 100Gi
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      app: gitlab