#Redis
spring:
  redis:
    #host: 192.168.2.11
    #port: 30379
    host: redis-master.mydlqcloud
    port: 6379
    password: 123456

#Log Config
logging:
  path: /opt/logs/

#Eureka Config
eureka:
  client:
    service-url:
      #defaultZone: http://192.168.2.11:31011/eureka/
      defaultZone: http://eureka-0.eureka.mydlqcloud:8080/eureka/,http://eureka-1.eureka.mydlqcloud:8080/eureka/,http://eureka-2.eureka.mydlqcloud:8080/eureka/

#Ribbon Timeout Config
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 5000
  SocketTimeout: 2000

#Hystrix Config
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#Zuul Config
zuul:
  retryable: false
  add-host-header: false
  prefix: /v1
  routes:
    helloworld:
      path: /helloworld/**
      serviceId: springboot-helloworld
  ratelimit:
    enabled: true
    key-prefix: retelimit
    repository: redis
    behind-proxy: true
    add-response-headers: true
    # globle retelimit config
    default-policy-list:
      - limit: 10
        quota: 100
        refresh-interval: 10
    # single service config
    policy-list:
      helloworld:
        - limit: 5
          quota: 100
          refresh-interval: 10