apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  accessModes:       
    - ReadWriteOnce
  capacity:          
    storage: 5Gi
  mountOptions:   #NFS挂在选项
    - hard 
    - nfsvers=4.1 #NFS Server版本
  nfs:            #NFS设置
    server: 192.168.2.11
    path: /nfs/data/postgres
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  #设置大小为5G
  selector:
    matchLabels:
      app: postgres