spring:
  redis:
    database: 0     
    timeout: 1000           
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 20 
        max-wait: -1      
        min-idle: 0       
        max-idle: 10