apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    k8s-app: prometheus
spec:
  capacity:          
    storage: 50Gi
  accessModes:       
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs: 
    server: 192.168.2.11 
    path: /nfs/prometheus
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus
  labels:
    k8s-app: prometheus  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      k8s-app: prometheus
